/**
 * Copyright (c) 2011-2013 INRIA.
 * 
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 **/
package fr.inria.eventcloud.delayers;

import fr.inria.eventcloud.api.Quadruple;
import fr.inria.eventcloud.configuration.EventCloudProperties;
import fr.inria.eventcloud.delayers.actions.ThreeInOneAction;
import fr.inria.eventcloud.delayers.buffers.ExtendedCompoundEvent;
import fr.inria.eventcloud.delayers.buffers.ThreeInOneBuffer;
import fr.inria.eventcloud.overlay.SemanticCanOverlay;
import fr.inria.eventcloud.pubsub.Subscription;

/**
 * A delayer class in charge of gathering the multiple delayers instances used
 * by the publish/subscribe layer. It concerns publish requests made with SBCE1,
 * 2 and 3 but also subscriptions and rewritten subscriptions generated by SBCE1
 * and 2.
 * 
 * @author lpellegr
 */
public final class PublishSubscribeDelayer extends Delayer<Object> {

    // private final Delayer<Quadruple> quadrupleDelayer;
    //
    // private final Delayer<Subscription> subscriptionDelayer;
    //
    // private final Delayer<ExtendedCompoundEvent> compoundEventDelayer;

    private final ThreeInOneBuffer buffer;

    public PublishSubscribeDelayer(SemanticCanOverlay overlay) {
        super(
                overlay,
                new ThreeInOneBuffer(overlay, getCommitSize()),
                new ThreeInOneAction(
                        overlay,
                        EventCloudProperties.PUBLISH_SUBSCRIBE_DELAYER_THREAD_POOL_SIZE.getValue()),
                getCommitInterval(), getCommitSize());

        this.buffer = (ThreeInOneBuffer) super.buffer;

        // FIXME: a better solution is to have one delayer per element to manage
        // (quadruple, subscription and compound event). However, having one
        // delayer per element means that several thread may flush data in
        // parallel. Consequently, some race conditions may occur and some
        // events not notified. A synchronization between delayers requires more
        // investigation.

        // this.quadrupleDelayer =
        // new Delayer<Quadruple>(
        // overlay,
        // "quadruples",
        // new QuadrupleBuffer(
        // overlay,
        // EventCloudProperties.PUBLISH_SUBSCRIBE_QUADRUPLE_DELAYER_COMMIT_SIZE.getValue()),
        // new QuadrupleAction(
        // overlay,
        // EventCloudProperties.PUBLISH_SUBSCRIBE_QUADRUPLE_DELAYER_THREAD_POOL_SIZE.getValue()),
        // EventCloudProperties.PUBLISH_SUBSCRIBE_QUADRUPLE_DELAYER_COMMIT_INTERVAL.getValue(),
        // EventCloudProperties.PUBLISH_SUBSCRIBE_QUADRUPLE_DELAYER_COMMIT_SIZE.getValue());
        //
        // this.subscriptionDelayer =
        // new Delayer<Subscription>(
        // overlay,
        // "subscriptions",
        // new SubscriptionBuffer(
        // overlay,
        // EventCloudProperties.PUBLISH_SUBSCRIBE_SUBSCRIPTION_DELAYER_COMMIT_SIZE.getValue()),
        // new SubscriptionAction(
        // overlay,
        // EventCloudProperties.PUBLISH_SUBSCRIBE_SUBSCRIPTION_DELAYER_THREAD_POOL_SIZE.getValue()),
        // EventCloudProperties.PUBLISH_SUBSCRIBE_SUBSCRIPTION_DELAYER_COMMIT_INTERVAL.getValue(),
        // EventCloudProperties.PUBLISH_SUBSCRIBE_SUBSCRIPTION_DELAYER_COMMIT_SIZE.getValue());
        //
        // if (EventCloudProperties.isSbce3PubSubAlgorithmUsed()) {
        // this.compoundEventDelayer =
        // new Delayer<ExtendedCompoundEvent>(
        // overlay,
        // "subscriptions",
        // new CompoundEventBuffer(
        // overlay,
        // EventCloudProperties.PUBLISH_SUBSCRIBE_COMPOUND_EVENT_DELAYER_COMMIT_SIZE.getValue()),
        // new CompoundEventAction(
        // overlay,
        // EventCloudProperties.PUBLISH_SUBSCRIBE_COMPOUND_EVENT_DELAYER_THREAD_POOL_SIZE.getValue()),
        // EventCloudProperties.PUBLISH_SUBSCRIBE_COMPOUND_EVENT_DELAYER_COMMIT_INTERVAL.getValue(),
        // EventCloudProperties.PUBLISH_SUBSCRIBE_COMPOUND_EVENT_DELAYER_COMMIT_SIZE.getValue());
        // } else {
        // this.compoundEventDelayer = null;
        // }
    }

    private static final int getCommitInterval() {
        if (!EventCloudProperties.isSbce3PubSubAlgorithmUsed()
                && EventCloudProperties.PUBLISH_SUBSCRIBE_DELAYER_COMMIT_INTERVAL.getValue() == EventCloudProperties.PUBLISH_SUBSCRIBE_DELAYER_COMMIT_INTERVAL.getDefaultValue()) {
            return EventCloudProperties.PUBLISH_SUBSCRIBE_DELAYER_COMMIT_INTERVAL.getValue() / 4;
        } else {
            return EventCloudProperties.PUBLISH_SUBSCRIBE_DELAYER_COMMIT_INTERVAL.getValue();
        }
    }

    private static final int getCommitSize() {
        if (!EventCloudProperties.isSbce3PubSubAlgorithmUsed()
                && EventCloudProperties.PUBLISH_SUBSCRIBE_DELAYER_COMMIT_SIZE.getValue() == EventCloudProperties.PUBLISH_SUBSCRIBE_DELAYER_COMMIT_SIZE.getDefaultValue()) {
            return EventCloudProperties.PUBLISH_SUBSCRIBE_DELAYER_COMMIT_SIZE.getValue() / 4;
        } else {
            return EventCloudProperties.PUBLISH_SUBSCRIBE_DELAYER_COMMIT_SIZE.getValue();
        }
    }

    public void receive(ExtendedCompoundEvent event) {
        synchronized (this.buffer) {
            this.buffer.add(event);
            this.commitOrCreateCommitThread();
        }
    }

    public void receive(Quadruple q) {
        synchronized (this.buffer) {
            this.buffer.add(q);
            this.commitOrCreateCommitThread();
        }
    }

    public void receive(Subscription s) {
        synchronized (this.buffer) {
            this.buffer.add(s);
            this.commitOrCreateCommitThread();
        }
    }

}
