// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/sparql-results.proto

package fr.inria.eventcloud.protobuf;

public final class SparqlResultsProtos {
  private SparqlResultsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BindingOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .eventcloud.Binding.SequenceBinding parent_binding = 1;
    java.util.List<fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding> 
        getParentBindingList();
    fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding getParentBinding(int index);
    int getParentBindingCount();
    java.util.List<? extends fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBindingOrBuilder> 
        getParentBindingOrBuilderList();
    fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBindingOrBuilder getParentBindingOrBuilder(
        int index);
    
    // repeated .eventcloud.Binding.SequenceBinding binding = 2;
    java.util.List<fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding> 
        getBindingList();
    fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding getBinding(int index);
    int getBindingCount();
    java.util.List<? extends fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBindingOrBuilder> 
        getBindingOrBuilderList();
    fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBindingOrBuilder getBindingOrBuilder(
        int index);
  }
  public static final class Binding extends
      com.google.protobuf.GeneratedMessage
      implements BindingOrBuilder {
    // Use Binding.newBuilder() to construct.
    private Binding(Builder builder) {
      super(builder);
    }
    private Binding(boolean noInit) {}
    
    private static final Binding defaultInstance;
    public static Binding getDefaultInstance() {
      return defaultInstance;
    }
    
    public Binding getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fr.inria.eventcloud.protobuf.SparqlResultsProtos.internal_static_eventcloud_Binding_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fr.inria.eventcloud.protobuf.SparqlResultsProtos.internal_static_eventcloud_Binding_fieldAccessorTable;
    }
    
    public interface SequenceBindingOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required string var_name = 1;
      boolean hasVarName();
      String getVarName();
      
      // required string value = 2;
      boolean hasValue();
      String getValue();
    }
    public static final class SequenceBinding extends
        com.google.protobuf.GeneratedMessage
        implements SequenceBindingOrBuilder {
      // Use SequenceBinding.newBuilder() to construct.
      private SequenceBinding(Builder builder) {
        super(builder);
      }
      private SequenceBinding(boolean noInit) {}
      
      private static final SequenceBinding defaultInstance;
      public static SequenceBinding getDefaultInstance() {
        return defaultInstance;
      }
      
      public SequenceBinding getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fr.inria.eventcloud.protobuf.SparqlResultsProtos.internal_static_eventcloud_Binding_SequenceBinding_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fr.inria.eventcloud.protobuf.SparqlResultsProtos.internal_static_eventcloud_Binding_SequenceBinding_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required string var_name = 1;
      public static final int VAR_NAME_FIELD_NUMBER = 1;
      private java.lang.Object varName_;
      public boolean hasVarName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getVarName() {
        java.lang.Object ref = varName_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            varName_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getVarNameBytes() {
        java.lang.Object ref = varName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          varName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // required string value = 2;
      public static final int VALUE_FIELD_NUMBER = 2;
      private java.lang.Object value_;
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getValue() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            value_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      private void initFields() {
        varName_ = "";
        value_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasVarName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasValue()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getVarNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getValueBytes());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getVarNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getValueBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBindingOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return fr.inria.eventcloud.protobuf.SparqlResultsProtos.internal_static_eventcloud_Binding_SequenceBinding_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return fr.inria.eventcloud.protobuf.SparqlResultsProtos.internal_static_eventcloud_Binding_SequenceBinding_fieldAccessorTable;
        }
        
        // Construct using fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          varName_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.getDescriptor();
        }
        
        public fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding getDefaultInstanceForType() {
          return fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.getDefaultInstance();
        }
        
        public fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding build() {
          fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding buildPartial() {
          fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding result = new fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.varName_ = varName_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding) {
            return mergeFrom((fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding other) {
          if (other == fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.getDefaultInstance()) return this;
          if (other.hasVarName()) {
            setVarName(other.getVarName());
          }
          if (other.hasValue()) {
            setValue(other.getValue());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasVarName()) {
            
            return false;
          }
          if (!hasValue()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                varName_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                value_ = input.readBytes();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required string var_name = 1;
        private java.lang.Object varName_ = "";
        public boolean hasVarName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getVarName() {
          java.lang.Object ref = varName_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            varName_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setVarName(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          varName_ = value;
          onChanged();
          return this;
        }
        public Builder clearVarName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          varName_ = getDefaultInstance().getVarName();
          onChanged();
          return this;
        }
        void setVarName(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          varName_ = value;
          onChanged();
        }
        
        // required string value = 2;
        private java.lang.Object value_ = "";
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public String getValue() {
          java.lang.Object ref = value_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            value_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setValue(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = getDefaultInstance().getValue();
          onChanged();
          return this;
        }
        void setValue(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
        }
        
        // @@protoc_insertion_point(builder_scope:eventcloud.Binding.SequenceBinding)
      }
      
      static {
        defaultInstance = new SequenceBinding(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:eventcloud.Binding.SequenceBinding)
    }
    
    // repeated .eventcloud.Binding.SequenceBinding parent_binding = 1;
    public static final int PARENT_BINDING_FIELD_NUMBER = 1;
    private java.util.List<fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding> parentBinding_;
    public java.util.List<fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding> getParentBindingList() {
      return parentBinding_;
    }
    public java.util.List<? extends fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBindingOrBuilder> 
        getParentBindingOrBuilderList() {
      return parentBinding_;
    }
    public int getParentBindingCount() {
      return parentBinding_.size();
    }
    public fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding getParentBinding(int index) {
      return parentBinding_.get(index);
    }
    public fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBindingOrBuilder getParentBindingOrBuilder(
        int index) {
      return parentBinding_.get(index);
    }
    
    // repeated .eventcloud.Binding.SequenceBinding binding = 2;
    public static final int BINDING_FIELD_NUMBER = 2;
    private java.util.List<fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding> binding_;
    public java.util.List<fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding> getBindingList() {
      return binding_;
    }
    public java.util.List<? extends fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBindingOrBuilder> 
        getBindingOrBuilderList() {
      return binding_;
    }
    public int getBindingCount() {
      return binding_.size();
    }
    public fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding getBinding(int index) {
      return binding_.get(index);
    }
    public fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBindingOrBuilder getBindingOrBuilder(
        int index) {
      return binding_.get(index);
    }
    
    private void initFields() {
      parentBinding_ = java.util.Collections.emptyList();
      binding_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getParentBindingCount(); i++) {
        if (!getParentBinding(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getBindingCount(); i++) {
        if (!getBinding(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < parentBinding_.size(); i++) {
        output.writeMessage(1, parentBinding_.get(i));
      }
      for (int i = 0; i < binding_.size(); i++) {
        output.writeMessage(2, binding_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < parentBinding_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, parentBinding_.get(i));
      }
      for (int i = 0; i < binding_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, binding_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements fr.inria.eventcloud.protobuf.SparqlResultsProtos.BindingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fr.inria.eventcloud.protobuf.SparqlResultsProtos.internal_static_eventcloud_Binding_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fr.inria.eventcloud.protobuf.SparqlResultsProtos.internal_static_eventcloud_Binding_fieldAccessorTable;
      }
      
      // Construct using fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getParentBindingFieldBuilder();
          getBindingFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (parentBindingBuilder_ == null) {
          parentBinding_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          parentBindingBuilder_.clear();
        }
        if (bindingBuilder_ == null) {
          binding_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          bindingBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.getDescriptor();
      }
      
      public fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding getDefaultInstanceForType() {
        return fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.getDefaultInstance();
      }
      
      public fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding build() {
        fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding buildPartial() {
        fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding result = new fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding(this);
        int from_bitField0_ = bitField0_;
        if (parentBindingBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            parentBinding_ = java.util.Collections.unmodifiableList(parentBinding_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.parentBinding_ = parentBinding_;
        } else {
          result.parentBinding_ = parentBindingBuilder_.build();
        }
        if (bindingBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            binding_ = java.util.Collections.unmodifiableList(binding_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.binding_ = binding_;
        } else {
          result.binding_ = bindingBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding) {
          return mergeFrom((fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding other) {
        if (other == fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.getDefaultInstance()) return this;
        if (parentBindingBuilder_ == null) {
          if (!other.parentBinding_.isEmpty()) {
            if (parentBinding_.isEmpty()) {
              parentBinding_ = other.parentBinding_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureParentBindingIsMutable();
              parentBinding_.addAll(other.parentBinding_);
            }
            onChanged();
          }
        } else {
          if (!other.parentBinding_.isEmpty()) {
            if (parentBindingBuilder_.isEmpty()) {
              parentBindingBuilder_.dispose();
              parentBindingBuilder_ = null;
              parentBinding_ = other.parentBinding_;
              bitField0_ = (bitField0_ & ~0x00000001);
              parentBindingBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getParentBindingFieldBuilder() : null;
            } else {
              parentBindingBuilder_.addAllMessages(other.parentBinding_);
            }
          }
        }
        if (bindingBuilder_ == null) {
          if (!other.binding_.isEmpty()) {
            if (binding_.isEmpty()) {
              binding_ = other.binding_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureBindingIsMutable();
              binding_.addAll(other.binding_);
            }
            onChanged();
          }
        } else {
          if (!other.binding_.isEmpty()) {
            if (bindingBuilder_.isEmpty()) {
              bindingBuilder_.dispose();
              bindingBuilder_ = null;
              binding_ = other.binding_;
              bitField0_ = (bitField0_ & ~0x00000002);
              bindingBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBindingFieldBuilder() : null;
            } else {
              bindingBuilder_.addAllMessages(other.binding_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getParentBindingCount(); i++) {
          if (!getParentBinding(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getBindingCount(); i++) {
          if (!getBinding(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.Builder subBuilder = fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addParentBinding(subBuilder.buildPartial());
              break;
            }
            case 18: {
              fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.Builder subBuilder = fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addBinding(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .eventcloud.Binding.SequenceBinding parent_binding = 1;
      private java.util.List<fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding> parentBinding_ =
        java.util.Collections.emptyList();
      private void ensureParentBindingIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          parentBinding_ = new java.util.ArrayList<fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding>(parentBinding_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding, fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.Builder, fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBindingOrBuilder> parentBindingBuilder_;
      
      public java.util.List<fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding> getParentBindingList() {
        if (parentBindingBuilder_ == null) {
          return java.util.Collections.unmodifiableList(parentBinding_);
        } else {
          return parentBindingBuilder_.getMessageList();
        }
      }
      public int getParentBindingCount() {
        if (parentBindingBuilder_ == null) {
          return parentBinding_.size();
        } else {
          return parentBindingBuilder_.getCount();
        }
      }
      public fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding getParentBinding(int index) {
        if (parentBindingBuilder_ == null) {
          return parentBinding_.get(index);
        } else {
          return parentBindingBuilder_.getMessage(index);
        }
      }
      public Builder setParentBinding(
          int index, fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding value) {
        if (parentBindingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParentBindingIsMutable();
          parentBinding_.set(index, value);
          onChanged();
        } else {
          parentBindingBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setParentBinding(
          int index, fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.Builder builderForValue) {
        if (parentBindingBuilder_ == null) {
          ensureParentBindingIsMutable();
          parentBinding_.set(index, builderForValue.build());
          onChanged();
        } else {
          parentBindingBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addParentBinding(fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding value) {
        if (parentBindingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParentBindingIsMutable();
          parentBinding_.add(value);
          onChanged();
        } else {
          parentBindingBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addParentBinding(
          int index, fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding value) {
        if (parentBindingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParentBindingIsMutable();
          parentBinding_.add(index, value);
          onChanged();
        } else {
          parentBindingBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addParentBinding(
          fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.Builder builderForValue) {
        if (parentBindingBuilder_ == null) {
          ensureParentBindingIsMutable();
          parentBinding_.add(builderForValue.build());
          onChanged();
        } else {
          parentBindingBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addParentBinding(
          int index, fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.Builder builderForValue) {
        if (parentBindingBuilder_ == null) {
          ensureParentBindingIsMutable();
          parentBinding_.add(index, builderForValue.build());
          onChanged();
        } else {
          parentBindingBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllParentBinding(
          java.lang.Iterable<? extends fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding> values) {
        if (parentBindingBuilder_ == null) {
          ensureParentBindingIsMutable();
          super.addAll(values, parentBinding_);
          onChanged();
        } else {
          parentBindingBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearParentBinding() {
        if (parentBindingBuilder_ == null) {
          parentBinding_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          parentBindingBuilder_.clear();
        }
        return this;
      }
      public Builder removeParentBinding(int index) {
        if (parentBindingBuilder_ == null) {
          ensureParentBindingIsMutable();
          parentBinding_.remove(index);
          onChanged();
        } else {
          parentBindingBuilder_.remove(index);
        }
        return this;
      }
      public fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.Builder getParentBindingBuilder(
          int index) {
        return getParentBindingFieldBuilder().getBuilder(index);
      }
      public fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBindingOrBuilder getParentBindingOrBuilder(
          int index) {
        if (parentBindingBuilder_ == null) {
          return parentBinding_.get(index);  } else {
          return parentBindingBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBindingOrBuilder> 
           getParentBindingOrBuilderList() {
        if (parentBindingBuilder_ != null) {
          return parentBindingBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(parentBinding_);
        }
      }
      public fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.Builder addParentBindingBuilder() {
        return getParentBindingFieldBuilder().addBuilder(
            fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.getDefaultInstance());
      }
      public fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.Builder addParentBindingBuilder(
          int index) {
        return getParentBindingFieldBuilder().addBuilder(
            index, fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.getDefaultInstance());
      }
      public java.util.List<fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.Builder> 
           getParentBindingBuilderList() {
        return getParentBindingFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding, fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.Builder, fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBindingOrBuilder> 
          getParentBindingFieldBuilder() {
        if (parentBindingBuilder_ == null) {
          parentBindingBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding, fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.Builder, fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBindingOrBuilder>(
                  parentBinding_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          parentBinding_ = null;
        }
        return parentBindingBuilder_;
      }
      
      // repeated .eventcloud.Binding.SequenceBinding binding = 2;
      private java.util.List<fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding> binding_ =
        java.util.Collections.emptyList();
      private void ensureBindingIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          binding_ = new java.util.ArrayList<fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding>(binding_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding, fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.Builder, fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBindingOrBuilder> bindingBuilder_;
      
      public java.util.List<fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding> getBindingList() {
        if (bindingBuilder_ == null) {
          return java.util.Collections.unmodifiableList(binding_);
        } else {
          return bindingBuilder_.getMessageList();
        }
      }
      public int getBindingCount() {
        if (bindingBuilder_ == null) {
          return binding_.size();
        } else {
          return bindingBuilder_.getCount();
        }
      }
      public fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding getBinding(int index) {
        if (bindingBuilder_ == null) {
          return binding_.get(index);
        } else {
          return bindingBuilder_.getMessage(index);
        }
      }
      public Builder setBinding(
          int index, fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding value) {
        if (bindingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBindingIsMutable();
          binding_.set(index, value);
          onChanged();
        } else {
          bindingBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setBinding(
          int index, fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.Builder builderForValue) {
        if (bindingBuilder_ == null) {
          ensureBindingIsMutable();
          binding_.set(index, builderForValue.build());
          onChanged();
        } else {
          bindingBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addBinding(fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding value) {
        if (bindingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBindingIsMutable();
          binding_.add(value);
          onChanged();
        } else {
          bindingBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addBinding(
          int index, fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding value) {
        if (bindingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBindingIsMutable();
          binding_.add(index, value);
          onChanged();
        } else {
          bindingBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addBinding(
          fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.Builder builderForValue) {
        if (bindingBuilder_ == null) {
          ensureBindingIsMutable();
          binding_.add(builderForValue.build());
          onChanged();
        } else {
          bindingBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addBinding(
          int index, fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.Builder builderForValue) {
        if (bindingBuilder_ == null) {
          ensureBindingIsMutable();
          binding_.add(index, builderForValue.build());
          onChanged();
        } else {
          bindingBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllBinding(
          java.lang.Iterable<? extends fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding> values) {
        if (bindingBuilder_ == null) {
          ensureBindingIsMutable();
          super.addAll(values, binding_);
          onChanged();
        } else {
          bindingBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearBinding() {
        if (bindingBuilder_ == null) {
          binding_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          bindingBuilder_.clear();
        }
        return this;
      }
      public Builder removeBinding(int index) {
        if (bindingBuilder_ == null) {
          ensureBindingIsMutable();
          binding_.remove(index);
          onChanged();
        } else {
          bindingBuilder_.remove(index);
        }
        return this;
      }
      public fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.Builder getBindingBuilder(
          int index) {
        return getBindingFieldBuilder().getBuilder(index);
      }
      public fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBindingOrBuilder getBindingOrBuilder(
          int index) {
        if (bindingBuilder_ == null) {
          return binding_.get(index);  } else {
          return bindingBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBindingOrBuilder> 
           getBindingOrBuilderList() {
        if (bindingBuilder_ != null) {
          return bindingBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(binding_);
        }
      }
      public fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.Builder addBindingBuilder() {
        return getBindingFieldBuilder().addBuilder(
            fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.getDefaultInstance());
      }
      public fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.Builder addBindingBuilder(
          int index) {
        return getBindingFieldBuilder().addBuilder(
            index, fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.getDefaultInstance());
      }
      public java.util.List<fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.Builder> 
           getBindingBuilderList() {
        return getBindingFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding, fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.Builder, fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBindingOrBuilder> 
          getBindingFieldBuilder() {
        if (bindingBuilder_ == null) {
          bindingBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding, fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.Builder, fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBindingOrBuilder>(
                  binding_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          binding_ = null;
        }
        return bindingBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:eventcloud.Binding)
    }
    
    static {
      defaultInstance = new Binding(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:eventcloud.Binding)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eventcloud_Binding_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eventcloud_Binding_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eventcloud_Binding_SequenceBinding_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eventcloud_Binding_SequenceBinding_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'src/main/resources/sparql-results.prot" +
      "o\022\neventcloud\"\260\001\n\007Binding\022;\n\016parent_bind" +
      "ing\030\001 \003(\0132#.eventcloud.Binding.SequenceB" +
      "inding\0224\n\007binding\030\002 \003(\0132#.eventcloud.Bin" +
      "ding.SequenceBinding\0322\n\017SequenceBinding\022" +
      "\020\n\010var_name\030\001 \002(\t\022\r\n\005value\030\002 \002(\tB3\n\034fr.i" +
      "nria.eventcloud.protobufB\023SparqlResultsP" +
      "rotos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_eventcloud_Binding_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_eventcloud_Binding_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eventcloud_Binding_descriptor,
              new java.lang.String[] { "ParentBinding", "Binding", },
              fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.class,
              fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.Builder.class);
          internal_static_eventcloud_Binding_SequenceBinding_descriptor =
            internal_static_eventcloud_Binding_descriptor.getNestedTypes().get(0);
          internal_static_eventcloud_Binding_SequenceBinding_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eventcloud_Binding_SequenceBinding_descriptor,
              new java.lang.String[] { "VarName", "Value", },
              fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.class,
              fr.inria.eventcloud.protobuf.SparqlResultsProtos.Binding.SequenceBinding.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
